name: ci
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
      - name: Setup Node.js version
        uses: actions/setup-node@main
        with:
          node-version: 14.x
      - name: Get short Github SHA
        id: vars
        run: |
          echo ::set-output name=sha_short::$(git rev-parse --short ${{ github.sha }})
      - name: Deploy to Github pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: src
          COMMIT_MESSAGE: Deploy to gh-pages from @ ${{ steps.vars.outputs.sha_short }}
          GIT_CONFIG_NAME: github-actions
          GIT_CONFIG_EMAIL: actions@github.com
      - name: Generate release body
        run: |
          npx rexreplace "(#+ \[\d+\.\d+\.\d+].*?)#+ \[?\d+\.\d+\.\d+]?" "_" -s -M -G -m -o "CHANGELOG.md" > RELEASE_BODY.md
          result=$(cat RELEASE_BODY.md)

          if [[ $? != 0 ]]; then
              echo "Command failed."
              exit 1;
          elif [[ $result ]]; then
              echo "Release body generated."
          else
              echo "This is the first release, useing different command to generate release body."
              npx rexreplace "(#+ \[?\d+\.\d+\.\d+]?.*)" "_" -s -M -G -m -o "CHANGELOG.md" > RELEASE_BODY.md
          fi
      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
          body_path: RELEASE_BODY.md
